### ISSUE TITLE
Regarding the dataset and how to display the final sampled images

### ISSUE THREAD

**Issue by daixingyu1** [kimdanni/Diffusion-Models-as-Masked-Autoencoders#2]
Thank you for taking the time to respond to my previous question. Currently, I have encountered some new issues and hope you can help me with them.
Regarding the dataset, are you using the ImageNet ILSVRC dataset? I noticed that the ILSVRC dataset is quite large, with the training and validation sets totaling over 100GB. Are there any smaller datasets that can be used as alternatives?
Regarding the sampled images, I found that this project does not seem to have code to display the final sampled images. How can I display the final sampled images?
Looking forward to your reply.

**Comment by kimdanni** [comment]
The code will be refactored and released. Thank you
